-- Generated by scripts/export_schema.py. Do not edit.
--
-- The canonical Aura schema, as the Alembic migrations build it on SQLite.
-- The Python app runs the migrations; the Android app applies this file. Both
-- therefore get the same tables, indexes and metrics views from one source.
--
-- Alembic revision: 0004

CREATE TABLE raw_records (
	id INTEGER NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	kind VARCHAR(32) NOT NULL, 
	external_id VARCHAR(128), 
	payload JSON NOT NULL, 
	content_hash VARCHAR(64) NOT NULL, 
	fetched_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	processed_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_raw_records_source_hash UNIQUE (source, content_hash)
);

CREATE TABLE oauth_tokens (
	service VARCHAR(32) NOT NULL, 
	payload JSON NOT NULL, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (service)
);

CREATE TABLE exercises (
	id INTEGER NOT NULL, 
	name VARCHAR(128) NOT NULL, 
	category VARCHAR(64), 
	modality VARCHAR(32) DEFAULT 'weight_reps' NOT NULL, 
	is_archived BOOLEAN DEFAULT 0 NOT NULL, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	CONSTRAINT ck_exercises_modality CHECK (modality IN ('weight_reps','bodyweight_reps','weighted_bodyweight','distance_time','duration'))
);

CREATE TABLE exercise_muscles (
	exercise_id INTEGER NOT NULL, 
	muscle VARCHAR(48) NOT NULL, 
	is_primary BOOLEAN DEFAULT 1 NOT NULL, 
	PRIMARY KEY (exercise_id, muscle), 
	FOREIGN KEY(exercise_id) REFERENCES exercises (id) ON DELETE CASCADE
);

CREATE TABLE workouts (
	id INTEGER NOT NULL, 
	performed_on DATE NOT NULL, 
	started_at DATETIME, 
	ended_at DATETIME, 
	notes TEXT, 
	source VARCHAR(32) DEFAULT 'manual' NOT NULL, 
	external_id VARCHAR(128), 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_workouts_source_external UNIQUE (source, external_id)
);

CREATE TABLE sets (
	id INTEGER NOT NULL, 
	workout_id INTEGER NOT NULL, 
	exercise_id INTEGER NOT NULL, 
	position INTEGER DEFAULT '0' NOT NULL, 
	weight_kg NUMERIC(7, 3), 
	reps INTEGER, 
	rpe NUMERIC(3, 1), 
	distance_m NUMERIC(10, 2), 
	duration_s INTEGER, 
	is_warmup BOOLEAN DEFAULT 0 NOT NULL, 
	notes TEXT, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(workout_id) REFERENCES workouts (id) ON DELETE CASCADE, 
	FOREIGN KEY(exercise_id) REFERENCES exercises (id), 
	CONSTRAINT ck_sets_reps_non_negative CHECK (reps IS NULL OR reps >= 0), 
	CONSTRAINT ck_sets_weight_non_negative CHECK (weight_kg IS NULL OR weight_kg >= 0), 
	CONSTRAINT ck_sets_rpe_range CHECK (rpe IS NULL OR (rpe >= 1 AND rpe <= 10))
);

CREATE TABLE activities (
	id INTEGER NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	external_id VARCHAR(128) NOT NULL, 
	sport_type VARCHAR(48) NOT NULL, 
	name TEXT, 
	started_at DATETIME NOT NULL, 
	timezone VARCHAR(64), 
	distance_m NUMERIC(12, 2), 
	moving_time_s INTEGER, 
	elapsed_time_s INTEGER, 
	elevation_gain_m NUMERIC(8, 2), 
	average_hr NUMERIC(5, 1), 
	max_hr NUMERIC(5, 1), 
	average_speed_ms NUMERIC(8, 3), 
	calories NUMERIC(8, 1), 
	raw_record_id BIGINT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(raw_record_id) REFERENCES raw_records (id), 
	CONSTRAINT uq_activities_source_external UNIQUE (source, external_id)
);

CREATE TABLE daily_metrics (
	date DATE NOT NULL, 
	metric VARCHAR(32) NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	value NUMERIC(12, 3) NOT NULL, 
	unit VARCHAR(16) NOT NULL, 
	recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (date, metric, source)
);

CREATE TABLE coach_notes (
	id INTEGER NOT NULL, 
	kind VARCHAR(32) NOT NULL, 
	content TEXT NOT NULL, 
	is_active BOOLEAN DEFAULT 1 NOT NULL, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_coach_notes_kind CHECK (kind IN ('injury','goal','preference','block','constraint'))
);

CREATE TABLE conversations (
	id INTEGER NOT NULL, 
	title TEXT, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
);

CREATE TABLE chat_messages (
	id INTEGER NOT NULL, 
	conversation_id INTEGER NOT NULL, 
	role VARCHAR(16) NOT NULL, 
	content JSON NOT NULL, 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE
);

CREATE TABLE sync_runs (
	id INTEGER NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	started_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	finished_at DATETIME, 
	status VARCHAR(16) DEFAULT 'running' NOT NULL, 
	records_read INTEGER DEFAULT '0' NOT NULL, 
	records_written INTEGER DEFAULT '0' NOT NULL, 
	error TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE app_settings (
	"key" VARCHAR(64) NOT NULL, 
	value JSON NOT NULL, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY ("key")
);

CREATE INDEX ix_raw_records_source_external ON raw_records (source, external_id);

CREATE UNIQUE INDEX ix_exercises_name_lower ON exercises (lower(name));

CREATE INDEX ix_workouts_performed_on ON workouts (performed_on);

CREATE INDEX ix_sets_workout_id ON sets (workout_id);

CREATE INDEX ix_sets_exercise_id ON sets (exercise_id);

CREATE INDEX ix_activities_started_at ON activities (started_at);

CREATE INDEX ix_daily_metrics_metric_date ON daily_metrics (metric, date);

CREATE INDEX ix_chat_messages_conversation_id ON chat_messages (conversation_id);

CREATE INDEX ix_sync_runs_source ON sync_runs (source);

CREATE VIEW v_sets_enriched AS
        SELECT
            s.id,
            s.workout_id,
            w.performed_on,
            s.exercise_id,
            e.name        AS exercise,
            e.category,
            e.modality,
            s.weight_kg,
            s.reps,
            s.rpe,
            s.distance_m,
            s.duration_s,
            s.is_warmup,
            COALESCE(s.weight_kg, 0) * COALESCE(s.reps, 0) AS volume_kg,
            CASE
                WHEN s.reps BETWEEN 1 AND 12 AND s.weight_kg > 0
                THEN ROUND(s.weight_kg * (1 + s.reps / 30.0), 2)
            END AS e1rm_kg
        FROM sets s
        JOIN workouts  w ON w.id = s.workout_id
        JOIN exercises e ON e.id = s.exercise_id;

CREATE VIEW v_daily_volume AS
        SELECT
            performed_on AS date,
            SUM(volume_kg) AS volume_kg,
            COUNT(*) AS working_sets,
            COUNT(DISTINCT exercise_id) AS exercises
        FROM v_sets_enriched
        WHERE NOT is_warmup
        GROUP BY performed_on;

CREATE VIEW v_weekly_muscle_volume AS
        SELECT
            date(v.performed_on, 'weekday 0', '-6 days') AS week_start,
            COALESCE(m.muscle, v.category, 'Uncategorised') AS muscle,
            SUM(v.volume_kg) AS volume_kg,
            COUNT(*) AS working_sets
        FROM v_sets_enriched v
        LEFT JOIN exercise_muscles m
               ON m.exercise_id = v.exercise_id AND m.is_primary
        WHERE NOT v.is_warmup
        GROUP BY 1, 2;

CREATE VIEW v_exercise_e1rm_daily AS
        SELECT
            exercise_id,
            exercise,
            performed_on AS date,
            MAX(e1rm_kg)   AS best_e1rm_kg,
            MAX(weight_kg) AS top_weight_kg,
            SUM(volume_kg) AS volume_kg,
            COUNT(*)       AS working_sets
        FROM v_sets_enriched
        WHERE NOT is_warmup
        GROUP BY exercise_id, exercise, performed_on;

CREATE VIEW v_daily_metrics_preferred AS
        SELECT date, metric, value, unit, source
        FROM (
            SELECT
                date, metric, value, unit, source,
                ROW_NUMBER() OVER (
                    PARTITION BY date, metric
                    ORDER BY CASE source
                        WHEN 'manual'         THEN 0
                        WHEN 'health_connect' THEN 1
                        WHEN 'gadgetbridge'   THEN 2
                        WHEN 'strava'         THEN 3
                        ELSE 9
                    END
                ) AS rank
            FROM daily_metrics
        ) ranked
        WHERE rank = 1;

CREATE VIEW v_daily_load AS
        WITH RECURSIVE spine("date") AS (
            SELECT date('now', '-365 days')
            UNION ALL
            SELECT date(sp."date", '+1 day') FROM spine sp WHERE sp."date" < date('now')
        ),
        strength AS (
            SELECT performed_on AS "date", SUM(volume_kg) / 1000.0 AS tonnes
            FROM v_sets_enriched
            WHERE NOT is_warmup
            GROUP BY performed_on
        ),
        cardio AS (
            SELECT
                date(started_at) AS "date",
                SUM(COALESCE(moving_time_s, 0)) / 60.0 AS minutes,
                SUM(COALESCE(distance_m, 0)) / 1000.0  AS km
            FROM activities
            GROUP BY 1
        )
        SELECT
            spine."date" AS date,
            COALESCE(st.tonnes, 0)  AS strength_tonnes,
            COALESCE(c.minutes, 0)  AS cardio_minutes,
            COALESCE(c.km, 0)       AS cardio_km,
            -- Arbitrary but consistent: 1 tonne lifted ~ 10 cardio minutes.
            -- ACWR needs the scale stable over time, not physically meaningful.
            COALESCE(st.tonnes, 0) + COALESCE(c.minutes, 0) / 10.0 AS load_au
        FROM spine
        LEFT JOIN strength st ON st."date" = spine."date"
        LEFT JOIN cardio   c  ON c."date"  = spine."date";

CREATE VIEW v_training_load AS
        SELECT
            date,
            strength_tonnes,
            cardio_minutes,
            cardio_km,
            load_au,
            ROUND(AVG(load_au) OVER w7, 3)  AS acute_7d,
            ROUND(AVG(load_au) OVER w28, 3) AS chronic_28d,
            CASE
                WHEN AVG(load_au) OVER w28 > 0
                THEN ROUND(AVG(load_au) OVER w7 / AVG(load_au) OVER w28, 3)
            END AS acwr
        FROM v_daily_load
        WINDOW
            w7  AS (ORDER BY date ROWS BETWEEN 6  PRECEDING AND CURRENT ROW),
            w28 AS (ORDER BY date ROWS BETWEEN 27 PRECEDING AND CURRENT ROW);
