"""Emit the canonical SQLite schema for the Android app.

The Kotlin app and the Python app must agree about the database down to the
last view, because the views are where every number the coach quotes comes
from. Rather than write the schema twice, this builds a throwaway database with
the real migrations and dumps what they produced.

`tests/test_schema_export.py` regenerates this and compares, so drift is a
failing test rather than a wrong number on a phone.

    uv run python ../scripts/export_schema.py          # rewrite the asset
    uv run python ../scripts/export_schema.py --check  # exit 1 if stale
"""

from __future__ import annotations

import sqlite3
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
API_DIR = REPO_ROOT / "api"
TARGET = REPO_ROOT / "android/core/src/main/resources/aura/schema.sql"

HEADER = """\
-- Generated by scripts/export_schema.py. Do not edit.
--
-- The canonical Aura schema, as the Alembic migrations build it on SQLite.
-- The Python app runs the migrations; the Android app applies this file. Both
-- therefore get the same tables, indexes and metrics views from one source.
--
-- Alembic revision: {revision}
"""


def build_schema_sql() -> str:
    """Run the migrations into a scratch database and dump what they made."""
    with tempfile.TemporaryDirectory() as tmp:
        database = Path(tmp) / "schema.db"

        sys.path.insert(0, str(API_DIR))
        from alembic.config import Config

        from alembic import command

        config = Config(str(API_DIR / "alembic.ini"))
        config.set_main_option("script_location", str(API_DIR / "alembic"))
        # Passed explicitly rather than through DATABASE_URL: app.config builds
        # its settings singleton at import time, so an environment variable set
        # here would already be too late to be read.
        config.set_main_option("sqlalchemy.url", f"sqlite:///{database}")
        config.attributes["configure_logger"] = False
        command.upgrade(config, "head")

        connection = sqlite3.connect(database)
        try:
            revision = connection.execute("SELECT version_num FROM alembic_version").fetchone()[0]
            statements: list[str] = []
            # sqlite_master is in creation order, which already respects foreign
            # key dependencies. Autoindexes have no SQL and are recreated
            # implicitly by their table's UNIQUE clause.
            for kind in ("table", "index", "view"):
                for (sql,) in connection.execute(
                    "SELECT sql FROM sqlite_master"
                    " WHERE type = ? AND sql IS NOT NULL AND name NOT LIKE 'sqlite_%'"
                    "   AND name <> 'alembic_version'"
                    " ORDER BY rowid",
                    (kind,),
                ):
                    statements.append(" ".join(sql.split()) if kind == "index" else sql.strip())
        finally:
            connection.close()

    body = ";\n\n".join(statements)
    return HEADER.format(revision=revision) + "\n" + body + ";\n"


def main() -> int:
    generated = build_schema_sql()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current == generated:
            print(f"{TARGET.relative_to(REPO_ROOT)} is up to date.")
            return 0
        print(
            f"{TARGET.relative_to(REPO_ROOT)} is stale. "
            "Run: uv run python ../scripts/export_schema.py",
            file=sys.stderr,
        )
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated)
    print(f"Wrote {TARGET.relative_to(REPO_ROOT)} ({len(generated.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
