"""Emit the coach's tool surface for the Android app.

The tool specs are pure data: names, descriptions and JSON Schema. Copying them
into Kotlin by hand would mean the phone's coach and the desktop's could end up
able to answer different questions, or — worse — describing the same tool
differently to the model, which changes what it does with it.

So they are generated, like the schema. `api/tests/test_tools_export.py` fails
when this file falls behind, and the Kotlin side fails when it has no handler
for a tool declared here.

    cd api && uv run python ../scripts/export_tools.py
    cd api && uv run python ../scripts/export_tools.py --check
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
API_DIR = REPO_ROOT / "api"
TARGET = REPO_ROOT / "android/core/src/main/resources/aura/tools.json"
PROMPT_TARGET = REPO_ROOT / "android/core/src/main/resources/aura/system_prompt.txt"

sys.path.insert(0, str(API_DIR))


def build() -> str:
    from app.agent.tools import HANDLERS, TOOL_SPECS

    declared = [spec["name"] for spec in TOOL_SPECS]
    missing = [name for name in declared if name not in HANDLERS]
    if missing:
        raise SystemExit(f"Declared with no handler: {', '.join(missing)}")

    document = {
        "_comment": (
            "Generated by scripts/export_tools.py. Do not edit. "
            "The coach's tool surface, shared by the Python and Android apps."
        ),
        "tools": TOOL_SPECS,
    }
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def build_prompt() -> str:
    """The coach's instructions, exactly as the Python coach sends them.

    Exported for the same reason as the tools: two apps phrasing the brief
    differently are two coaches, and an eval run against one says nothing about
    the other. The date and remembered facts are appended at call time, by the
    same rules on both sides.
    """
    from app.agent.coach import SYSTEM_INSTRUCTIONS

    return SYSTEM_INSTRUCTIONS


def outputs() -> dict[Path, str]:
    return {TARGET: build(), PROMPT_TARGET: build_prompt()}


def main() -> int:
    produced = outputs()
    if "--check" in sys.argv:
        stale = [p for p, text in produced.items() if not p.exists() or p.read_text() != text]
        if not stale:
            print("Tool surface and system prompt are up to date.")
            return 0
        for path in stale:
            print(f"{path.relative_to(REPO_ROOT)} is stale.", file=sys.stderr)
        print("Run: uv run python ../scripts/export_tools.py", file=sys.stderr)
        return 1

    for path, text in produced.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"Wrote {path.relative_to(REPO_ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
