"""Emit the coach's tool surface for the Android app.

The tool specs are pure data: names, descriptions and JSON Schema. Copying them
into Kotlin by hand would mean the phone's coach and the desktop's could end up
able to answer different questions, or — worse — describing the same tool
differently to the model, which changes what it does with it.

So they are generated, like the schema. `api/tests/test_tools_export.py` fails
when this file falls behind, and the Kotlin side fails when it has no handler
for a tool declared here.

    cd api && uv run python ../scripts/export_tools.py
    cd api && uv run python ../scripts/export_tools.py --check
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
API_DIR = REPO_ROOT / "api"
TARGET = REPO_ROOT / "android/core/src/main/resources/aura/tools.json"

sys.path.insert(0, str(API_DIR))


def build() -> str:
    from app.agent.tools import HANDLERS, TOOL_SPECS

    declared = [spec["name"] for spec in TOOL_SPECS]
    missing = [name for name in declared if name not in HANDLERS]
    if missing:
        raise SystemExit(f"Declared with no handler: {', '.join(missing)}")

    document = {
        "_comment": (
            "Generated by scripts/export_tools.py. Do not edit. "
            "The coach's tool surface, shared by the Python and Android apps."
        ),
        "tools": TOOL_SPECS,
    }
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def main() -> int:
    generated = build()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current == generated:
            print(f"{TARGET.relative_to(REPO_ROOT)} is up to date.")
            return 0
        print(
            f"{TARGET.relative_to(REPO_ROOT)} is stale. "
            "Run: uv run python ../scripts/export_tools.py",
            file=sys.stderr,
        )
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated)
    count = len(json.loads(generated)["tools"])
    print(f"Wrote {TARGET.relative_to(REPO_ROOT)} ({count} tools).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
