"""Emit the starter workouts for the Android app.

The templates, and the catalogue entries their exercises come from, are
defined once in `api/app/workouts.py`. Both apps offer the same sessions
and create exercises with the same muscles, so volume by muscle means the
same thing whichever app logged the set.

    cd api && uv run python ../scripts/export_workouts.py
    cd api && uv run python ../scripts/export_workouts.py --check
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
API_DIR = REPO_ROOT / "api"
TARGET = REPO_ROOT / "android/core/src/main/resources/aura/workouts.json"

sys.path.insert(0, str(API_DIR))


def build() -> str:
    from app.workouts import document

    return json.dumps(
        {
            "_comment": (
                "Generated by scripts/export_workouts.py. Do not edit. "
                "The starter workouts, shared by the Python and Android apps."
            ),
            **document(),
        },
        indent=2,
    ) + "\n"


def main() -> int:
    text = build()
    if "--check" in sys.argv:
        if TARGET.exists() and TARGET.read_text() == text:
            print("Starter workouts are up to date.")
            return 0
        print(f"{TARGET.relative_to(REPO_ROOT)} is stale.", file=sys.stderr)
        print("Run: uv run python ../scripts/export_workouts.py", file=sys.stderr)
        return 1
    TARGET.write_text(text)
    print(f"Wrote {TARGET.relative_to(REPO_ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
